package org.linkstorage.model;
//org.linkstorage.model
// Generated Sep 25, 2010 8:24:27 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String nickname;
	private String channel;
	private Date createdAt;
	private Date updatedAt;
	private Set<Link> links = new HashSet<Link>(0);

	public Author() {
	}

	public Author(int id, String nickname, String channel, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.nickname = nickname;
		this.channel = channel;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Author(int id, String nickname, String channel, Date createdAt,
			Date updatedAt, Set<Link> links) {
		this.id = id;
		this.nickname = nickname;
		this.channel = channel;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.links = links;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Link> getLinks() {
		return this.links;
	}

	public void setLinks(Set<Link> links) {
		this.links = links;
	}

}
