package org.linkstorage.model;
// org.linkstorage.model
// Generated Sep 25, 2010 8:24:27 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Link generated by hbm2java
 */
@XmlRootElement(name="links")
public class Link implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Author author;
	private String url;
	private String metaDescription;
	private Date updatedAt;
	private Date createdAt;

	public Link() {
	}

	public Link(String url, Date updatedAt, Date createdAt) {
		this.url = url;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
	}

	public Link(Author author, String url, String metaDescription,
			Date updatedAt, Date createdAt) {
		this.author = author;
		this.url = url;
		this.metaDescription = metaDescription;
		this.updatedAt = updatedAt;
		this.createdAt = createdAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
